export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const CREATE_WORKSPACE_SUCCESS = "CREATE_WORKSPACE_SUCCESS";
export const CREATE_WORKSPACE_REJECT = "CREATE_WORKSPACE_REJECT";

export const UPLOAD_WORKSPACES = "UPLOAD_WORKSPACES";
export const UPLOAD_WORKSPACES_SUCCESS = "UPLOAD_WORKSPACES_SUCCESS";
export const UPLOAD_WORKSPACES_REJECT = "UPLOAD_WORKSPACES_REJECT";

export const SET_CURRENT_WORKSPACE = "SET_CURRENT_WORKSPACE";
export const DELETE_CURRENT_WORKSPACE = "DELETE_CURRENT_WORKSPACE";

export const SELECT_WORKSPACE = "SELECT_WORKSPACE";
