export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const CREATE_WORKSPACE_SUCCESS = "CREATE_WORKSPACE_SUCCESS";
export const CREATE_WORKSPACE_REJECT = "CREATE_WORKSPACE_REJECT";

export const UPLOAD_WORKSPACES = "UPLOAD_WORKSPACES";
export const UPLOAD_WORKSPACES_SUCCESS = "UPLOAD_WORKSPACES_SUCCESS";
export const UPLOAD_WORKSPACES_REJECT = "UPLOAD_WORKSPACES_REJECT";

export const LISTEN_WORKSPACE = "LISTEN_WORKSPACE";
export const LISTEN_WORKSPACE_SUCCESS = "LISTEN_WORKSPACE_SUCCESS";
export const LISTEN_WORKSPACE_REJECT = "LISTEN_WORKSPACE_REJECT";

export const DELETE_CURRENT_WORKSPACE = "DELETE_CURRENT_WORKSPACE";
