export const LISTEN_WORKSPACE = "LISTEN_WORKSPACE";
export const LISTEN_WORKSPACE_SUCCESS = "LISTEN_WORKSPACE_SUCCESS";
export const LISTEN_WORKSPACE_REJECT = "LISTEN_WORKSPACE_REJECT";

export const LISTEN_STOP = "LISTEN_STOP";
